# Paths to ignore
excluded:
  - Pods

# "Lets just be reasonable" overrides :)
file_length: 800
function_body_length: 80
function_parameter_count: 5
identifier_name: {min_length: 3}
line_length: 120
type_body_length: 800
type_name: {max_length: 50, min_length: 4}

# See all rules and descriptions here:
# https://github.com/realm/SwiftLint/blob/master/Rules.md

# Disabled Rules
disabled_rules:
  # These tend to be more annoying than helpful
  - trailing_whitespace
  - leading_whitespace
  - vertical_whitespace
  - trailing_newline

  # This increases readability at times
  - empty_parentheses_with_trailing_closure

  # Prevent griping about: let _ = …
  # Having the |let| makes giving it a name in debugging easier,
  # plus, it phrases it as a positive test rather than a negative one.
  - unused_optional_binding
  - redundant_discardable_let

# Opt-In Rules
opt_in_rules:
  # Prefer contains over first(where:) != nil
  - contains_over_first_not_nil
  # Types used for hosting only static members should be implemented as a caseless enum to avoid instantiation.
  - convenience_type
  # No Bool?
  - discouraged_optional_boolean
  # Prefer checking isEmpty over comparing count to zero.
  - empty_count
  # Prefer checking isEmpty over comparing count to zero.
  - empty_string
  # No empty funcs in test cases
  - empty_xctest_method
  # Explicitly calling .init() should be avoided.
  - explicit_init
  # Avoid force unwrapping other. IUO don't trigger on this rule
  - force_unwrapping
  # Call super on funcs like viewDidLoad
  - overridden_super_call
  # Make outlets private
  - private_outlet
  # Parentheses are not needed when declaring closure arguments.
  - unneeded_parentheses_in_closure_argument
  # Trailing closure syntax should be used whenever possible.
  - trailing_closure
