os:
  - linux
  env: SWIFT_SNAPSHOT=5.0.1
  - osx
  env: SWIFT_SNAPSHOT=5.0.1
language: generic
sudo: required
dist: trusty
osx_image: xcode10.3
before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git
script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
notifications:
  email: false
